### ISSUE TITLE
Support for Dictionary?

### ISSUE THREAD

**Issue by kathyjudd** [rexm/Handlebars.Net#106]
Hello all,
I'm working on converting my js handlebars templates for C#. I'm running into a problem where my dictionary<int, string> are not processed and the output doesn't have the html code for the dictionary in the output. If I replace dictionary with list<string> then it works fine and the content gets generated. Are there any options for getting dictionary support added ?

I'm currently using Handlebars.Net 1.6.4.

Thanks

**Comment by rexm** [comment]
Dictionary support has been there for awhile... Can you post your code?

**Comment by kathyjudd** [comment]
Sure, here is a simple demo.

`string html = @"
				<div>{{First}} {{Last}}</div>
				
				{{#each MyDictionary}}
					<p>{{@value}}</p>
				{{/each}}
			";

			TestClass test = new TestClass();
			test.First = "Jack";
			test.Last = "Smith";
			test.MyDictionary.Add( 0, "Test 1" );
			test.MyDictionary.Add( 1, "Test 2" );
			test.MyDictionary.Add( 2, "Test 3" );

			var template = HandlebarsDotNet.Handlebars.Compile( html );

			string result = template( test );`

Output:
`<div>Jack Smith</div>`

**Comment by rexm** [comment]
OK, looks like the issue here is using a primitive type for the dictionary key. We've never tested that use case. I'll add a fix to the backlog to support primitive keys in Dictionaries. In the meantime, you can make this scenario work by using a string (i.e. `"0"`. `"1"`, `"2"` instead of `0`,`1`,`2`) for your key instead of an integer.

**Comment by kathyjudd** [comment]
Thanks so much. You suggestion worked.
