### ISSUE TITLE
Invalidating compiled template function

### ISSUE THREAD

**Issue by sowee15** [rexm/Handlebars.Net#142]
Hi,

As I see it, it looks like invalidating (and freeing the memory used by) a compiled template function is as straight forward as stopping referencing the function. For instance, if I were to compile a template then store it using:

`handlebars.RegisterTemplate(name, template);`

I could then just remove the entry "name" from:

`configuration.RegisteredTemplates`

to invalidate it and free the memory used by it?

I want to validate that it does not create on-the-fly assemblies that are loaded into the app domain like the RazorEngine does.

Thanks!

**Comment by rexm** [comment]
It does create on-the-fly assemblies, and those are loaded into the AppDomain. I would redirect the question to what specific kind of memory pressure problem are you trying to solve?

**Comment by sowee15** [comment]
If our process is long-lived and templates are regularly updated, are we right to be concerned by the loaded symbols that will no longer be used (because they represent old versions of templates)?

I saw you are getting a delegate from an expression tree, is it a lot slower to use the delegate without adding it to a dynamic assembly (if possible at all)?

**Comment by rexm** [comment]
All things being equal, I would say it is not justified to be concerned about gradually increasing the process size. That's very normal, and Microsoft hasn't seen fit to spend the time and money to support unloading assemblies - so clearly the vast majority of use cases don't require it.

That's not to say your case isn't a corner case where that is painful - maybe you are doing something very unusual and loading hundreds of thousands or millions of assemblies (though on modern hardware even this shouldn't necessarily be a serious problem). If your specific situation is very unusual where this makes it a big problem, I'd look at other ways to mitigate, since process growth is a fundamental property of how .NET works. Don't fight your chosen platform :)

**Comment by sowee15** [comment]
You are right, we know it's by design, but it still itches to leave something behind that isn't used anymore, but we'll probably just accept it as I don't think our case it so unusual either.

Thanks for your input!
