### ISSUE TITLE
Default output of a {{ DateTime }} is different to JS implementation

### ISSUE THREAD

**Issue by arrkaye** [rexm/Handlebars.Net#292]
Using a DateTime in a template seems to just call ToString() on the DateTime, whereas in JS it output the ISO string.

This feels wrong. Is it?

**Comment by rexm** [comment]
Since our goal is functional and behavioral parity with the JS library, yes it is almost certainly wrong :) Unfortunately now that we have over a million installs, we are limited in the kinds of non-backwards-compatible changes we can roll out while we're still under version 1.x

Version 2.0 is percolating in my head and will have a lot of breaking changes to address these things.

**Comment by arrkaye** [comment]
Sounds great! Is there a way to introduce this particular change (or a mechanism for us to address these kinds of issues) in the current version, without breaking all the current users clients?

Perhaps allowing the injection of a custom object or property on the Handlebars configuration?

**Comment by rexm** [comment]
The simplest thing to do would be to use a helper

**Comment by 304NotModified** [comment]
If we change this, it would be nice to allow us the format the date.
