### ISSUE TITLE
Block helpers do not support inversions

### ISSUE THREAD

**Issue by rukeba** [rexm/Handlebars.Net#9]
Hello,

Thank you for great project! We try to migrate our .net project from mustache-sharp to Handlebars.Net.
Is there any way to register block helpers something like this (javascript)?

```javascript
Handlebars.registerHelper('ifCond', function(v1, v2, options) {
  if(v1 === v2) {
    return options.fn(this);
  }
  return options.inverse(this);
});
```

Usage:

```
{{#ifCond v1 v2}}
    {{v1}} is equal to {{v2}}
{{else}}
    {{v1}} is not equal to {{v2}}
{{/ifCond}}
```

I see HandlebarsBlockHelper delegate, but i can't find how to implement conditional logic inside helper.

**Comment by rexm** [comment]
In order to support this (and make helper functions a little more similar to how they look in the JS library), the block helper delegate signature was changed from:
```c#
public delegate void HandlebarsBlockHelper(TextWriter output, Action<TextWriter, object> template, dynamic context, params object[] arguments);
```
to:
```c#
public delegate void HandlebarsBlockHelper(TextWriter output, HelperOptions options, dynamic context, params object[] arguments);
```

The `HelperOptions` class has two properties, `Template` and `Inverse`. Both are of type `Action<TextWriter, object>` (same as everywhere else).

**Comment by rexm** [comment]
1.2.0 updated on NuGet

**Comment by rukeba** [comment]
Thank you.
