### ISSUE TITLE
Default value when item not found in context.

### ISSUE THREAD

**Issue by techfooting** [rexm/Handlebars.Net#95]
Is it possible to specify a default value to use instead of "" when an expression is not found in the context object?

If not, can you point me to the code file and method where that resolution happens so I can specify a default value?

**Comment by rexm** [comment]
Is it possible to do this in the official [handlebarsjs](http://handlebarsjs.com) library?

**Comment by techfooting** [comment]
I don't know if it's possible in handlebarsjs.  I've never used it.  I'm just starting to use Handlebars.Net.

**Comment by rexm** [comment]
I did a cursory search through and didn't see anything, so since our goal is parity with that library, it's unlikely we'll support it either.

There's constructs within the templating language itself to deal with that - it's slightly more verbose, but very explicit which is usually a good thing. For example, "#if propertyName then propertyName else defaultValue"

**Comment by techfooting** [comment]
yeah that's helpful but means a lot of possible template work if I don't know what may or may not be missing at run time.  What is the class/method where those context values are discovered?

**Comment by rexm** [comment]
Well, [PathBinder](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Compiler/Translation/Expression/PathBinder.cs) is a key part of value resolution. However, the display value for an [UndefinedBindingResult is determined by its ToString method.](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Compiler/Structure/UndefinedBindingResult.cs)

**Comment by techfooting** [comment]
Thanks for the pointers!
